package Biblioteca;


/**
* Biblioteca/GestionBibliotecaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Biblioteca.idl
* sábado 10 de mayo de 2025 16H26' CEST
*/

public interface GestionBibliotecaOperations 
{
  String obtenerLibro (String titulo);
  void agregarLibro (String titulo, String autor);

  // NUEVAS FUNCIONES (puedes usar estas o crear las tuyas):
  void eliminarLibro (String titulo);
  String buscarPorAutor (String autor);
} // interface GestionBibliotecaOperations
